#!/bin/sh

((dim=2))
for((i=1;i<=$1;++i))
do
  echo --- Input $i  ---
  echo Dim: $dim
  ((col=dim*2))
  ./genin.py $dim $col > input$i.txt
  #echo --- python ---
  #time tail -n 1 input$i.txt | ./strisce.py > output$i.py.txt
  echo ---   C++  ---
  time ./strisce < input$i.txt > output$i.cpp.txt
  echo ---    C   ---
  time ./collagec < input$i.txt > output$i.c.txt
  ((dim*=2))
  if((dim>1000))
  then
    ((dim=1000))
  fi
done
